### ISSUE TITLE
【ロゴ作成】

### ISSUE THREAD

**Issue by hajidon01** [syoukishimizu/FilmNotify#5]
# 概要
　

# ゴール
　アプリのロゴを完成

<img width="240" alt="（概要）" src="https://github.com/syoukishimizu/FilmNotify/assets/139446420/e8a1d165-2a62-4f64-b17a-9b51314e1b0a" />

# ツール
キャンバ

**Comment by hajidon01** [comment]
色は白黒でオケ

**Comment by syoukishimizu** [comment]
一旦青木のくれたパワポ貼っておくわ。
[「Fi-Fy」アプリロゴ案.pptx](https://github.com/syoukishimizu/FilmNotify/files/12040518/Fi-Fy.pptx)


個人的には15枚目と25枚目が好きかな。

[15枚目]
<img width="440" alt="スクリーンショット 2023-07-13 23 36 30" src="https://github.com/syoukishimizu/FilmNotify/assets/64625416/f500e30c-5088-48d5-beaa-fdfded8c0dac">

[25枚目]
<img width="418" alt="スクリーンショット 2023-07-13 23 37 17" src="https://github.com/syoukishimizu/FilmNotify/assets/64625416/7f85d89b-9a40-4fca-a89b-7538eca3a351">

**Comment by syoukishimizu** [comment]
あと、金ローみたいにするなら古めかしいも辞退とかもありなのかも

**Comment by syoukishimizu** [comment]
<image src="https://github.com/syoukishimizu/FilmNotify/assets/64625416/a97b491f-cf7f-4f1a-afea-f1b1ee13cf72" />
