### ISSUE TITLE
【検索で調べた際に、できればシリーズ作品などが公開順に表示されるようにしたい】

### ISSUE THREAD

**Issue by hajidon01** [syoukishimizu/FilmNotify#54]
# 概要

# ゴール

<img width="240" alt="（概要）" src=![image](https://github.com/syoukishimizu/FilmNotify/assets/139446420/529b62f5-8fab-4c7a-a921-4e1e15e8a182) />

# 注意点

**Comment by syoukishimizu** [comment]
修正ずみ
